/**
 * Speech-to-Text (STT) configuration options.
 */
export interface STTConfig {
  /** The STT provider to use (e.g., "deepgram", "google") */
  provider: string;
  /** Language code for speech recognition (e.g., "en-US", "es-ES") */
  language: string;
  /** Audio sample rate in Hz (e.g., 16000, 44100) */
  sample_rate: number;
  /** Number of audio channels (1 for mono, 2 for stereo) */
  channels: number;
  /** Whether to include punctuation in transcriptions */
  punctuation: boolean;
  /** Audio encoding format (e.g., "linear16", "opus") */
  encoding: string;
  /** STT model identifier to use */
  model: string;
}

/**
 * Word pronunciation override for text-to-speech.
 */
export interface Pronunciation {
  /** The word to be pronounced differently */
  word: string;
  /** Phonetic pronunciation or alternative spelling */
  pronunciation: string;
}

/**
 * Text-to-Speech (TTS) configuration options.
 */
export interface TTSConfig {
  /** The TTS provider to use (e.g., "elevenlabs", "google") */
  provider: string;
  /**
   * Voice identifier for the selected provider.
   * Optional because some providers expose defaults or infer from the model.
   */
  voice_id?: string;
  /**
   * Speech rate multiplier (e.g., 1.0 for normal, 1.5 for faster).
   * Optional to match spec defaults (server defaults to 1.0 when omitted).
   */
  speaking_rate?: number;
  /**
   * Audio format for TTS output (e.g., "mp3", "pcm").
   * Optional; falls back to provider defaults when not provided.
   */
  audio_format?: string;
  /**
   * Audio sample rate in Hz (e.g., 16000, 44100).
   * Optional; provider default is used when omitted.
   */
  sample_rate?: number;
  /**
   * Connection timeout in seconds.
   * Optional because the server applies its own defaults when the field is omitted.
   */
  connection_timeout?: number;
  /**
   * Request timeout in seconds.
   * Optional because the server applies its own defaults when the field is omitted.
   */
  request_timeout?: number;
  /** TTS model identifier to use */
  model: string;
  /**
   * Custom pronunciation overrides.
   * Optional so minimal payloads from the spec are accepted; defaults to an empty list when absent.
   */
  pronunciations?: Pronunciation[];
}

/**
 * LiveKit room configuration for real-time communication.
 */
export interface LiveKitConfig {
  /** LiveKit room name to join */
  room_name: string;
  /** Whether to enable session recording (defaults to false) */
  enable_recording?: boolean;
  /** Identity assigned to the agent participant (defaults to "sayna-ai") */
  sayna_participant_identity?: string;
  /** Display name for the agent participant (defaults to "Sayna AI") */
  sayna_participant_name?: string;
  /** Optional list of participant identities to monitor; defaults to empty array (all participants) */
  listen_participants?: string[];
}

/**
 * Configuration message sent to initialize the Sayna WebSocket connection.
 * @internal
 */
export interface ConfigMessage {
  type: "config";
  /** Session identifier used for recording paths; server generates a UUID when omitted */
  stream_id?: string;
  /** Whether audio streaming is enabled */
  audio?: boolean;
  /** Speech-to-text configuration (required when audio=true) */
  stt_config?: STTConfig;
  /** Text-to-speech configuration (required when audio=true) */
  tts_config?: TTSConfig;
  /** Optional LiveKit room configuration */
  livekit?: LiveKitConfig;
}

/**
 * Message to request text-to-speech synthesis.
 * @internal
 */
export interface SpeakMessage {
  type: "speak";
  /** Text to synthesize */
  text: string;
  /** Whether to flush the TTS queue before speaking */
  flush?: boolean;
  /** Whether this speech can be interrupted */
  allow_interruption?: boolean;
}

/**
 * Message to clear the TTS queue.
 * @internal
 */
export interface ClearMessage {
  type: "clear";
}

/**
 * Message to send data to the Sayna session.
 * @internal
 */
export interface SendMessageMessage {
  type: "send_message";
  /** Message content */
  message: string;
  /** Message role (e.g., "user", "assistant") */
  role: string;
  /** Optional topic identifier */
  topic?: string;
  /** Optional debug metadata */
  debug?: Record<string, unknown>;
}

/**
 * Message to request a SIP call transfer for the active LiveKit session.
 * LiveKit must be configured and a SIP participant must be active for this to succeed.
 */
export interface SipTransferMessage {
  type: "sip_transfer";
  /** Destination phone number or extension to transfer to */
  transfer_to: string;
}

/**
 * Message received when the Sayna connection is ready.
 */
export interface ReadyMessage {
  type: "ready";
  /** Session identifier; may be auto-generated by the server if not provided in config */
  stream_id?: string;
  /** LiveKit room name acknowledged by the server (present only when LiveKit is enabled) */
  livekit_room_name?: string;
  /** LiveKit WebSocket URL configured on the server (only present when LiveKit is enabled) */
  livekit_url?: string;
  /** Identity assigned to the agent participant when LiveKit is enabled (only present when LiveKit is enabled) */
  sayna_participant_identity?: string;
  /** Display name assigned to the agent participant when LiveKit is enabled (only present when LiveKit is enabled) */
  sayna_participant_name?: string;
}

/**
 * Speech-to-text transcription result.
 */
export interface STTResultMessage {
  type: "stt_result";
  /** Transcribed text */
  transcript: string;
  /** Whether this is a final transcription */
  is_final: boolean;
  /** Whether speech has concluded */
  is_speech_final: boolean;
  /** Transcription confidence score (0-1) */
  confidence: number;
}

/**
 * Error message from the Sayna server.
 */
export interface ErrorMessage {
  type: "error";
  /** Error description */
  message: string;
}

/**
 * SIP transfer specific error message from the Sayna server.
 */
export interface SipTransferErrorMessage {
  type: "sip_transfer_error";
  /** Human-readable error description */
  message: string;
}

/**
 * Message data from a Sayna session participant.
 */
export interface SaynaMessage {
  /** Message content */
  message?: string;
  /** Additional data payload */
  data?: string;
  /** Participant identity */
  identity: string;
  /** Message topic */
  topic: string;
  /** Room identifier */
  room: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
}

/**
 * Wrapper for participant messages.
 */
export interface MessageMessage {
  type: "message";
  /** The message data */
  message: SaynaMessage;
}

/**
 * Information about a session participant.
 */
export interface Participant {
  /** Unique participant identity */
  identity: string;
  /** Optional display name */
  name?: string;
  /** Room identifier */
  room: string;
  /** Unix timestamp in milliseconds */
  timestamp: number;
}

/**
 * Message received when a participant disconnects.
 */
export interface ParticipantDisconnectedMessage {
  type: "participant_disconnected";
  /** The disconnected participant */
  participant: Participant;
}

/**
 * Message received when the TTS playback is complete.
 */
export interface TTSPlaybackCompleteMessage {
  type: "tts_playback_complete";
  /** Unix timestamp in milliseconds */
  timestamp: number;
}

/**
 * Union type of all possible messages received from the Sayna server.
 */
export type OutgoingMessage =
  | ReadyMessage
  | STTResultMessage
  | ErrorMessage
  | SipTransferErrorMessage
  | MessageMessage
  | ParticipantDisconnectedMessage
  | TTSPlaybackCompleteMessage;

/**
 * Voice descriptor returned by the GET /voices endpoint.
 */
export interface Voice {
  /** Provider-specific identifier for the voice profile */
  id: string;
  /** URL to a preview audio sample (may be empty) */
  sample: string;
  /** Human-readable name supplied by the provider */
  name: string;
  /** Detected accent associated with the voice */
  accent: string;
  /** Inferred gender label from provider metadata */
  gender: string;
  /** Primary language for synthesis */
  language: string;
}

/**
 * Response from the GET /voices endpoint.
 * Keys are provider identifiers, values are arrays of voice descriptors.
 */
export type VoicesResponse = Record<string, Voice[]>;

/**
 * Response from the GET / health check endpoint.
 */
export interface HealthResponse {
  /** Status indicator, always "OK" when successful */
  status: string;
}

/**
 * Response from the POST /livekit/token endpoint.
 */
export interface LiveKitTokenResponse {
  /** JWT granting LiveKit permissions for the specified participant */
  token: string;
  /** Echo of the requested room */
  room_name: string;
  /** Echo of the requested identity */
  participant_identity: string;
  /** WebSocket endpoint for the LiveKit server */
  livekit_url: string;
}

/**
 * Participant information from a SIP webhook event.
 */
export interface WebhookSIPParticipant {
  /** Display name of the SIP participant (may be undefined if not provided) */
  name?: string;
  /** Unique identity assigned to the participant */
  identity: string;
  /** Participant session ID from LiveKit */
  sid: string;
}

/**
 * Room information from a SIP webhook event.
 */
export interface WebhookSIPRoom {
  /** Name of the LiveKit room */
  name: string;
  /** Room session ID from LiveKit */
  sid: string;
}

/**
 * SIP webhook payload sent from Sayna service.
 *
 * This represents a cryptographically signed webhook event forwarded by Sayna
 * when a SIP participant joins a LiveKit room. Use the WebhookReceiver class
 * to verify the signature and parse this payload securely.
 *
 * @see WebhookReceiver
 */
export interface WebhookSIPOutput {
  /** SIP participant information */
  participant: WebhookSIPParticipant;
  /** LiveKit room information */
  room: WebhookSIPRoom;
  /** Caller's phone number (E.164 format, e.g., "+15559876543") */
  from_phone_number: string;
  /** Called phone number (E.164 format, e.g., "+15551234567") */
  to_phone_number: string;
  /** Room name prefix configured in Sayna (e.g., "sip-") */
  room_prefix: string;
  /** SIP domain extracted from the To header (e.g., "example.com") */
  sip_host: string;
  /** SIP headers from the incoming call (key-value pairs, optional) */
  sip_headers?: Record<string, string>;
}

/**
 * A single SIP webhook hook configuration.
 */
export interface SipHook {
  /** SIP domain pattern (case-insensitive) */
  host: string;
  /** HTTPS URL to forward webhook events to */
  url: string;
  /**
   * Tenant identifier for this hook. This value is written to LiveKit room metadata
   * for inbound SIP calls routed through this hook.
   *
   * - When AUTH_REQUIRED=true on the server: `auth_id` must be non-empty.
   * - When AUTH_REQUIRED=false: `auth_id` may be an empty string (unauthenticated mode).
   *
   * Treat this as an opaque string; pass it through unchanged without client-side interpretation.
   */
  auth_id: string;
}

/**
 * Response from the GET /sip/hooks and POST /sip/hooks endpoints.
 */
export interface SipHooksResponse {
  /** List of configured SIP hooks */
  hooks: SipHook[];
}

/**
 * Request body for the POST /sip/hooks endpoint.
 */
export interface SetSipHooksRequest {
  /** List of hooks to add or replace */
  hooks: SipHook[];
}

/**
 * Request body for the DELETE /sip/hooks endpoint.
 */
export interface DeleteSipHooksRequest {
  /** List of host names to remove (case-insensitive) */
  hosts: string[];
}

/**
 * Summary information for a LiveKit room.
 * Returned by the GET /livekit/rooms endpoint.
 *
 * Room listings are scoped to the authenticated context; this endpoint may return
 * fewer rooms than before when authentication is enabled.
 */
export interface LiveKitRoomSummary {
  /** The room name. Room names are not rewritten by the SDK; scoping is enforced server-side. */
  name: string;
  /** Number of current participants in the room */
  num_participants: number;
  /** Room creation time (Unix timestamp in seconds) */
  creation_time: number;
}

/**
 * Response from the GET /livekit/rooms endpoint.
 *
 * Room listings are scoped to the authenticated context. When authentication is enabled,
 * this endpoint returns only rooms accessible to the current credentials.
 */
export interface LiveKitRoomsResponse {
  /** List of rooms accessible to the authenticated client */
  rooms: LiveKitRoomSummary[];
}

/**
 * Participant connection state in a LiveKit room.
 */
export type LiveKitParticipantState =
  | "JOINING"
  | "JOINED"
  | "ACTIVE"
  | "DISCONNECTED"
  | "UNKNOWN";

/**
 * Type/kind of participant in a LiveKit room.
 */
export type LiveKitParticipantKind =
  | "STANDARD"
  | "AGENT"
  | "SIP"
  | "EGRESS"
  | "INGRESS"
  | "UNKNOWN";

/**
 * Detailed information about a participant in a LiveKit room.
 * Returned as part of the GET /livekit/rooms/{room_name} response.
 */
export interface LiveKitParticipantInfo {
  /** Unique session ID for this participant (generated by LiveKit) */
  sid: string;
  /** Unique identifier provided when connecting */
  identity: string;
  /** Display name of the participant */
  name: string;
  /** Current connection state of the participant */
  state: LiveKitParticipantState;
  /** Type/kind of the participant (e.g., STANDARD, AGENT, SIP) */
  kind: LiveKitParticipantKind;
  /** Timestamp when participant joined (Unix timestamp in seconds) */
  joined_at: number;
  /** User-specified metadata for the participant */
  metadata: string;
  /** User-specified attributes for the participant */
  attributes: Record<string, string>;
  /** Whether the participant is currently publishing audio/video */
  is_publisher: boolean;
}

/**
 * Detailed information about a LiveKit room including participants.
 * Returned by the GET /livekit/rooms/{room_name} endpoint.
 *
 * A 404 response can mean "not found" or "not accessible" when room ownership
 * is enforced server-side.
 */
export interface LiveKitRoomDetails {
  /** Unique session ID for the room (generated by LiveKit) */
  sid: string;
  /** The room name. Room names are not rewritten by the SDK; scoping is enforced server-side. */
  name: string;
  /** Number of current participants in the room */
  num_participants: number;
  /** Maximum allowed participants (0 = no limit) */
  max_participants: number;
  /** Room creation time (Unix timestamp in seconds) */
  creation_time: number;
  /**
   * Room metadata as an opaque JSON string. Do not parse or rely on this for access decisions;
   * access is enforced server-side.
   */
  metadata: string;
  /** Whether a recording is currently active */
  active_recording: boolean;
  /** List of participants currently in the room */
  participants: LiveKitParticipantInfo[];
}

/**
 * Request body for the DELETE /livekit/participant endpoint.
 * Used to remove a participant from a LiveKit room.
 *
 * A 404 response can mean "not found" or "not accessible" when room ownership is enforced.
 */
export interface RemoveLiveKitParticipantRequest {
  /** The LiveKit room name where the participant is connected. Room names are clean; the SDK does not rewrite them. */
  room_name: string;
  /** The identity of the participant to remove */
  participant_identity: string;
}

/**
 * Response from the DELETE /livekit/participant endpoint.
 * Confirms the participant removal operation.
 */
export interface RemoveLiveKitParticipantResponse {
  /** Status of the removal operation (e.g., "removed") */
  status: string;
  /** The room name where the participant was removed */
  room_name: string;
  /** The identity of the removed participant */
  participant_identity: string;
}

/**
 * Request body for the POST /livekit/participant/mute endpoint.
 * Used to mute or unmute a participant's track in a LiveKit room.
 *
 * A 404 response can mean "not found" or "not accessible" when room ownership is enforced.
 */
export interface MuteLiveKitParticipantRequest {
  /** The LiveKit room name where the participant is connected. Room names are clean; the SDK does not rewrite them. */
  room_name: string;
  /** The identity of the participant whose track to mute */
  participant_identity: string;
  /** The session ID of the track to mute/unmute */
  track_sid: string;
  /** True to mute, false to unmute */
  muted: boolean;
}

/**
 * Response from the POST /livekit/participant/mute endpoint.
 * Confirms the mute/unmute operation.
 */
export interface MuteLiveKitParticipantResponse {
  /** The room name where the operation was performed */
  room_name: string;
  /** The identity of the participant */
  participant_identity: string;
  /** The session ID of the track */
  track_sid: string;
  /** Current muted state after the operation */
  muted: boolean;
}

/**
 * Status of a SIP transfer operation.
 * - "initiated": Transfer has been started but not yet confirmed complete
 * - "completed": Transfer has been successfully completed
 */
export type SipTransferStatus = "initiated" | "completed";

/**
 * Request body for the POST /sip/transfer endpoint.
 * Used to initiate a SIP call transfer for a participant in a LiveKit room.
 *
 * A 404 response can mean "not found" or "not accessible" when room ownership is enforced.
 */
export interface SipTransferRequest {
  /** The LiveKit room name where the SIP participant is connected. Room names are clean; the SDK does not rewrite them. */
  room_name: string;
  /** The identity of the SIP participant to transfer */
  participant_identity: string;
  /** The phone number to transfer the call to (international, national, or extension format) */
  transfer_to: string;
}

/**
 * Response from the POST /sip/transfer endpoint.
 * Confirms the SIP transfer operation status.
 */
export interface SipTransferResponse {
  /** Status of the transfer request ("initiated" or "completed") */
  status: SipTransferStatus;
  /** The room name where the transfer was initiated */
  room_name: string;
  /** The identity of the participant being transferred */
  participant_identity: string;
  /** The normalized phone number with tel: prefix */
  transfer_to: string;
}

/**
 * Optional per-request SIP configuration overrides for outbound calls.
 * When provided, these values override the server's global SIP configuration.
 */
export interface SipCallSipConfig {
  /** SIP server address override. Format: `hostname` or `hostname:port` */
  outbound_address?: string | null;
  /** SIP authentication username override */
  auth_username?: string | null;
  /** SIP authentication password override */
  auth_password?: string | null;
}

/**
 * Request body for the POST /sip/call endpoint.
 * Used to initiate an outbound SIP call to a phone number.
 */
export interface SipCallRequest {
  /** LiveKit room name to place the call in */
  room_name: string;
  /** Display name for the participant in the room */
  participant_name: string;
  /** Unique identity for the participant */
  participant_identity: string;
  /** Caller's phone number (E.164 format, e.g., "+15105550123") */
  from_phone_number: string;
  /** Destination phone number (E.164 format, e.g., "+15551234567") */
  to_phone_number: string;
  /** Optional per-request SIP configuration overrides */
  sip?: SipCallSipConfig;
}

/**
 * Response from the POST /sip/call endpoint.
 * Confirms the outbound SIP call has been initiated.
 */
export interface SipCallResponse {
  /** Status of the call initiation (always "initiated") */
  status: "initiated";
  /** Echo of the room name where the call was placed */
  room_name: string;
  /** Echo of the participant identity */
  participant_identity: string;
  /** LiveKit participant ID for the SIP participant */
  participant_id: string;
  /** SIP call ID for tracking */
  sip_call_id: string;
}
